name: Generate PHP Documentation

on:
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        run: |
          docker-compose up -d # Starts your existing Docker environment
          
      # Install phpDocumentor inside the Docker container
      - name: Install phpDocumentor in Docker container
        run: |
          docker-compose exec <your-service-name> bash -c "curl -O https://phpdoc.org/phpDocumentor.phar && chmod +x phpDocumentor.phar"

      # Generate documentation
      - name: Run phpDocumentor inside Docker container
        run: |
          docker-compose exec <your-service-name> bash -c "./phpDocumentor.phar -d ./src -t ./docs"

      # Commit and push documentation to a specific branch
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git checkout -b gh-pages
          git add -f docs/ # Assuming phpDocumentor stores the generated docs in a "docs" folder
          git commit -m "Update PHP documentation"
          git push --force --set-upstream origin gh-pages